# For gdrive

client_config_backend: settings
client_config:
  client_id: 898231813242-a0l97elerrmvigqlp2jvj30n737vg5t3.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive